---
Parameters:
  DBClusterMasterUserPassword:
    Type: String
    NoEcho: True
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: !If [ Foobar, !Ref DBClusterMasterUserPassword, !Ref 'AWS::NoValue' ]
      MasterUsername: !If [ Foobar, admin, !Ref 'AWS::NoValue' ]
      Port: 3306
