---
Parameters:
  DBClusterMasterUserPassword:
    Type: String
    NoEcho: True
  DBSnapshotName:
    Default: ''
    Type: String
Conditions: 
  UseDBSnapshot: !Not [!Equals [!Ref DBSnapshotName, '']]
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: !If [ UseDBSnapshot, !Ref 'AWS::NoValue', !Ref DBClusterMasterUserPassword ]
      MasterUsername: !If [ UseDBSnapshot, !Ref 'AWS::NoValue', admin ]
      Port: 3306
